### ISSUE TITLE
佬，我部署后页面没有显示，怎么解决啊？

### ISSUE THREAD

**Issue by XingJi-love** [ZhongxuYang/vitepress-plugin-music#2]
![image](https://github.com/user-attachments/assets/fef583b7-4f74-48d6-9077-460e78dcfe38)

![屏幕截图 2024-11-25 221917](https://github.com/user-attachments/assets/3b9cb720-db30-4e16-9c2c-cef8407df2a9)

**Comment by ZhongxuYang** [comment]
hi👋，我在本地没有复现出此问题。

这个项目是开源项目吗？（是的话可以把地址提供给我）或者提供一个最小代码实现。

**Comment by XingJi-love** [comment]
佬这是我的博客地址：https://vitepress.xingji.fun/ ，可以帮我看看为啥没显示吗？
预览时出现这个API报错，查阅解决方法（第二张图片）的程序，也从新安装过Sass，问题也没有解决
![image](https://github.com/user-attachments/assets/95b8632b-0cb9-4198-8c95-c21a968eb143)
![image](https://github.com/user-attachments/assets/f64a7a4e-f9c7-4dd4-89e9-4f755570659a)

**Comment by ZhongxuYang** [comment]
Done.
