### ISSUE TITLE
佬我部署好了，但是本地预览可以播放，打包（我在dist文件里面没有看到打包的歌曲）部署后显示无法播放，怎么解决？

### ISSUE THREAD

**Issue by XingJi-love** [ZhongxuYang/vitepress-plugin-music#3]
这个是本地预览的
![屏幕截图 2024-12-18 160955](https://github.com/user-attachments/assets/d6da5f92-dd0c-4186-a678-9ef739fa83d2)
这个是部署后的
![屏幕截图 2024-12-18 161012](https://github.com/user-attachments/assets/7483f403-30dc-4037-b78a-9a85a93ebea2)
怎么解决阿佬？

**Comment by ZhongxuYang** [comment]
应该是你的.mp3文件没有放在publicDir内造成的。

**Comment by XingJi-love** [comment]
佬，我是这样放置的
![屏幕截图 2024-12-18 165254](https://github.com/user-attachments/assets/92fc1b9c-c966-4918-9025-78ddc31bfaa3)
配置上是这样的
```js
const playlist = [
  {
    name: '起风了-买辣椒也用券',
    author: '买辣椒也用券',
    file: './mp3/起风了-买辣椒也用券.mp3',
  },
]
```

**Comment by ZhongxuYang** [comment]
把 `mp3` 文件夹移动到 `/docs/public` 内（移动后的目录是：`/docs/public/mp3`）。

然后 `playlist` 内的 `file` 字段修改为 `file: '/mp3/起风了-买辣椒也用券.mp3'` 的格式（也就是`./` 去掉 `.`）。

**Comment by XingJi-love** [comment]
好的佬，我试试，谢谢了

**Comment by ZhongxuYang** [comment]
Done.
